name: realview_task
description: "Recruitment task"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2
  cupertino_icons: 1.0.8
  get_it: 8.1.0
  freezed: 3.2.0
  retrofit: 4.6.0
  logger: 2.6.1
  json_annotation: 4.9.0
  freezed_annotation: 3.1.0
  flutter_bloc: 9.1.1
  bloc_test: 10.0.0
  injectable: 2.5.1
  dio: 5.8.0+1
  multiple_result: 5.2.0
  go_router: 16.0.0
  equatable: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.6.0
  flutter_lints: 5.0.0
  json_serializable: 6.10.0
  retrofit_generator: 10.0.1
  injectable_generator: 2.8.0
  mockito: 5.5.0

flutter:
  uses-material-design: true
